// ============================================================
// USER TYPES
// ============================================================

/*
 * User roles supported by the backend.
 *
 * "user"  → normal job seeker account
 * "admin" → administrator with additional access
 */
export type Role = "user" | "admin";

export interface User {
  id: number;
  name: string;
  email: string;
  role: Role;
}

// ============================================================
// APPLICATION TYPES
// ============================================================

/*
 * Status values must match the backend/database ENUM.
 *
 * Keeping these values as a union type prevents accidental
 * invalid status strings from being used in the frontend.
 */
export type ApplicationStatus =
  | "applied"
  | "interviewing"
  | "offer"
  | "rejected"
  | "withdrawn";

export interface Application {
  id: number;

  /*
   * ID of the user who owns this application.
   */
  user_id: number;

  company_name: string;
  job_title: string;

  /*
   * The job link is optional because an application can exist
   * without a saved job posting URL.
   */
  job_link?: string;

  status: ApplicationStatus;

  /*
   * Stored as a string because the API returns date values
   * that are serialized from MySQL.
   */
  applied_date: string;

  notes?: string;

  /*
   * These fields are generated by the database, so they are
   * optional because not every API response necessarily needs
   * to include them.
   */
  created_at?: string;
  updated_at?: string;
}

// ============================================================
// INTERVIEW TYPES
// ============================================================

/*
 * Interview delivery methods supported by the backend.
 */
export type InterviewMode =
  | "online"
  | "offline"
  | "phone";

/*
 * Interview lifecycle states supported by the backend.
 */
export type InterviewStatus =
  | "scheduled"
  | "completed"
  | "cancelled";

export interface Interview {
  id: number;

  /*
   * Connects this interview to its parent application.
   */
  application_id: number;

  round_name: string;

  /*
   * Interview date/time is returned by the API as a string.
   */
  interview_date: string;

  mode: InterviewMode;
  status: InterviewStatus;

  notes?: string;

  /*
   * The database creates this timestamp automatically.
   */
  created_at?: string;
}